trigger:
  branches:
    include:
      - main

pool:
  name: prod-pool

variables:
  backendServiceConnection: 'su-sc'
  backendResourceGroup: 'YOUR_BACKEND_RG'
  backendStorageAccount: 'pipelinestg1'
  backendContainer: 'pipelinecnt1'
  backendKey: 'pipeline.tfstate'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

stages:

#=========================
# Stage 1 - Init
#=========================
- stage: Init
  displayName: Terraform Init

  jobs:
  - job: Init
    steps:

    - checkout: self

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(backendServiceConnection)'
        backendAzureRmResourceGroupName: '$(backendResourceGroup)'
        backendAzureRmStorageAccountName: '$(backendStorageAccount)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: '$(backendKey)'
        workingDirectory: '$(workingDirectory)'

#=========================
# Stage 2 - Validate
#=========================
- stage: Validate
  displayName: Terraform Validate
  dependsOn: Init

  jobs:
  - job: Validate

    steps:

    - checkout: self

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(backendServiceConnection)'
        backendAzureRmResourceGroupName: '$(backendResourceGroup)'
        backendAzureRmStorageAccountName: '$(backendStorageAccount)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: '$(backendKey)'
        workingDirectory: '$(workingDirectory)'

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(workingDirectory)'

#=========================
# Stage 3 - Plan
#=========================
- stage: Plan
  displayName: Terraform Plan
  dependsOn: Validate

  jobs:
  - job: Plan

    steps:

    - checkout: self

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(backendServiceConnection)'
        backendAzureRmResourceGroupName: '$(backendResourceGroup)'
        backendAzureRmStorageAccountName: '$(backendStorageAccount)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: '$(backendKey)'
        workingDirectory: '$(workingDirectory)'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(workingDirectory)'
        environmentServiceNameAzureRM: '$(backendServiceConnection)'
        commandOptions: '-var-file="environments/dev/terraform.tfvars" -out="dev.tfplan"'

#=========================
# Stage 4 - Apply
#=========================
- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan

  jobs:
  - job: Apply

    steps:

    - checkout: self

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(backendServiceConnection)'
        backendAzureRmResourceGroupName: '$(backendResourceGroup)'
        backendAzureRmStorageAccountName: '$(backendStorageAccount)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: '$(backendKey)'
        workingDirectory: '$(workingDirectory)'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(workingDirectory)'
        environmentServiceNameAzureRM: '$(backendServiceConnection)'
        commandOptions: '-auto-approve -var-file="environments/dev/terraform.tfvars"'